server:
  port: 8081
  max-http-request-header-size: 10KB
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/vixhr_auth
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  session:
    jdbc:
      initialize-schema: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 30

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    oauth:
      client-id: test-client
      client-secret: secret
  oAuthFlow:
    tokenUrl: http://localhost:8081/oauth2/token