CREATE TABLE departments
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    company_id  BIGINT                                  NOT NULL,
    name        VARCHAR(50)                             NOT NULL,
    description VARCHAR(50)                             NOT NULL,
    manager_id  BIGINT,
    CONSTRAINT pk_departments PRIMARY KEY (id)
);

CREATE TABLE employees
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    user_id          BIGINT                                  NOT NULL,
    company_id       BIGINT                                  NOT NULL,
    first_name       VARCHAR(50)                             NOT NULL,
    last_name        VARCHAR(50)                             NOT NULL,
    email            VARCHAR(255)                            NOT NULL,
    phone            VARCHAR(10),
    department_id    BIGINT                                  NOT NULL,
    joining_date     date                                    NOT NULL,
    termination_date date,
    employee_code    VARCHAR(255),
    base_salary      DOUBLE PRECISION                        NOT NULL,
    job_role_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE TABLE job_roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    company_id  BIGINT                                  NOT NULL,
    title       VARCHAR(50)                             NOT NULL,
    description VARCHAR(50),
    min_salary  DOUBLE PRECISION                        NOT NULL,
    max_salary  DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_job_roles PRIMARY KEY (id)
);

ALTER TABLE departments
    ADD CONSTRAINT uc_departments_company UNIQUE (company_id);

ALTER TABLE departments
    ADD CONSTRAINT uc_departments_name UNIQUE (name);

ALTER TABLE employees
    ADD CONSTRAINT uc_employees_email UNIQUE (email);

ALTER TABLE employees
    ADD CONSTRAINT uc_employees_employeecode UNIQUE (employee_code);

ALTER TABLE job_roles
    ADD CONSTRAINT uc_job_roles_company UNIQUE (company_id);

ALTER TABLE job_roles
    ADD CONSTRAINT uc_job_roles_title UNIQUE (title);

ALTER TABLE departments
    ADD CONSTRAINT FK_DEPARTMENTS_ON_MANAGER FOREIGN KEY (manager_id) REFERENCES employees (id);

ALTER TABLE employees
    ADD CONSTRAINT FK_EMPLOYEES_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (id);

ALTER TABLE employees
    ADD CONSTRAINT FK_EMPLOYEES_ON_JOB_ROLE FOREIGN KEY (job_role_id) REFERENCES job_roles (id);