-- Wipe all existing data
DELETE FROM departments;

CREATE TABLE job_roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    company_id  BIGINT                                  NOT NULL,
    title       VARCHAR(50)                             NOT NULL,
    description VARCHAR(50),
    min_salary  DOUBLE PRECISION                        NOT NULL,
    max_salary  DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_job_roles PRIMARY KEY (id)
);

ALTER TABLE departments
    ADD company_id BIGINT;

ALTER TABLE departments
    ALTER COLUMN company_id SET NOT NULL;

ALTER TABLE employees
    ADD company_id BIGINT;

ALTER TABLE employees
    ADD department_id BIGINT;

ALTER TABLE employees
    ADD employee_code VARCHAR(50);

ALTER TABLE employees
    ADD job_role_id BIGINT;

ALTER TABLE employees
    ADD phone VARCHAR(10);

ALTER TABLE employees
    ADD termination_date date;

ALTER TABLE employees
    ALTER COLUMN company_id SET NOT NULL;

ALTER TABLE employees
    ALTER COLUMN department_id SET NOT NULL;

ALTER TABLE departments
    ADD CONSTRAINT uc_departments_company UNIQUE (company_id);

ALTER TABLE employees
    ADD CONSTRAINT uc_employees_employeecode UNIQUE (employee_code);

ALTER TABLE job_roles
    ADD CONSTRAINT uc_job_roles_company UNIQUE (company_id);

ALTER TABLE job_roles
    ADD CONSTRAINT uc_job_roles_title UNIQUE (title);

ALTER TABLE employees
    ADD CONSTRAINT FK_EMPLOYEES_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (id);

ALTER TABLE employees
    ADD CONSTRAINT FK_EMPLOYEES_ON_JOB_ROLE FOREIGN KEY (job_role_id) REFERENCES job_roles (id);

ALTER TABLE employees
    DROP COLUMN department;

ALTER TABLE employees
    DROP COLUMN job_title;

ALTER TABLE employees
    ALTER COLUMN base_salary SET NOT NULL;

ALTER TABLE departments
    ALTER COLUMN description TYPE VARCHAR(50) USING (description::VARCHAR(50));

ALTER TABLE departments
    ALTER COLUMN description SET NOT NULL;

ALTER TABLE departments
    ALTER COLUMN manager_id SET NOT NULL;