server:
  port: 8083
  max-http-request-header-size: 10KB

spring:
  application:
    name: attendance-service
  datasource:
    url: jdbc:postgresql://localhost:5432/vixhr_attendance
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 30

springdoc:
  api-docs:
    enabled: true
    path: /attendance/v3/api-docs
  swagger-ui:
    enabled: false
  oAuthFlow:
    tokenUrl: http://localhost:8080/oauth2/token

openapi:
  service:
    title: ${spring.application.name}
    version: 1.0.0
    url: http://localhost:${server.port}