CREATE TABLE companies
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    tenant_id           BIGINT                                  NOT NULL,
    name                VARCHAR(50)                             NOT NULL,
    registration_number VARCHAR(50)                             NOT NULL,
    tax_id              VARCHAR(50),
    address             VARCHAR(100),
    phone               VARCHAR(10),
    email               VARCHAR(255),
    website             VARCHAR(50),
    city                VARCHAR(255),
    state               VARCHAR(255),
    country             VARCHAR(255),
    postal_code         VARCHAR(255),
    CONSTRAINT pk_companies PRIMARY KEY (id)
);

CREATE TABLE company_settings
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                TIMESTAMP WITHOUT TIME ZONE,
    updated_at                TIMESTAMP WITHOUT TIME ZONE,
    company_id                BIGINT                                  NOT NULL,
    working_days              JSONB                                   NOT NULL,
    standard_work_hours_start time WITHOUT TIME ZONE                  NOT NULL,
    standard_work_hours_end   time WITHOUT TIME ZONE                  NOT NULL,
    regular_hours_per_day     DOUBLE PRECISION                        NOT NULL,
    currency_code             VARCHAR(20)                             NOT NULL,
    date_format               VARCHAR(20)                             NOT NULL,
    time_format               VARCHAR(20)                             NOT NULL,
    enable_overtime           BOOLEAN                                 NOT NULL,
    enable_geo_location       BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_company_settings PRIMARY KEY (id)
);

CREATE TABLE holidays
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    company_id   BIGINT                                  NOT NULL,
    name         VARCHAR(100)                            NOT NULL,
    date         date                                    NOT NULL,
    is_recurring BOOLEAN                                 NOT NULL,
    description  VARCHAR(100),
    CONSTRAINT pk_holidays PRIMARY KEY (id)
);

CREATE TABLE overtime_policies
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    company_id          BIGINT                                  NOT NULL,
    name                VARCHAR(50)                             NOT NULL,
    rate_multiplier     DOUBLE PRECISION                        NOT NULL,
    start_time          time WITHOUT TIME ZONE                  NOT NULL,
    end_time            time WITHOUT TIME ZONE                  NOT NULL,
    applicable_days     JSONB,
    max_hours_per_day   DOUBLE PRECISION                        NOT NULL,
    max_hours_per_week  DOUBLE PRECISION                        NOT NULL,
    max_hours_per_month DOUBLE PRECISION                        NOT NULL,
    is_holiday          BOOLEAN                                 NOT NULL,
    requires_approval   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_overtime_policies PRIMARY KEY (id)
);

ALTER TABLE company_settings
    ADD CONSTRAINT uc_company_settings_company UNIQUE (company_id);

ALTER TABLE company_settings
    ADD CONSTRAINT FK_COMPANY_SETTINGS_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE holidays
    ADD CONSTRAINT FK_HOLIDAYS_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE overtime_policies
    ADD CONSTRAINT FK_OVERTIME_POLICIES_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);