server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Auth Service Routes
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/users/**

        # Employee Service Routes
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/employees/**

        # Attendance Service Routes
        - id: attendance-service
          uri: lb://attendance-service
          predicates:
            - Path=/api/attendance/**

        # Payroll Service Routes
        - id: payroll-service
          uri: lb://payroll-service
          predicates:
            - Path=/api/payroll/**

        # Notification Service Routes
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

        # Reporting Service Routes
        - id: reporting-service
          uri: lb://reporting-service
          predicates:
            - Path=/api/reports/**

        - id: actuator-routes
          uri: lb://api-gateway
          predicates:
            - Path=/actuator/**

        # OpenAPI Routes (Development Only)
        - id: employee-service-openapi-route
          uri: http://localhost:8082
          predicates:
            - Path=/employee/v3/api-docs
            - Method=GET

        - id: auth-service-openapi-route
          uri: http://localhost:8081
          predicates:
            - Path=/auth/v3/api-docs
            - Method=GET

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 30

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: employee-service
        url: /employee/v3/api-docs
      - name: auth-service
        url: /auth/v3/api-docs