CREATE TABLE features
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    name        VARCHAR(100)                            NOT NULL,
    code        VARCHAR(50)                             NOT NULL,
    description VARCHAR(500),
    module      VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_features PRIMARY KEY (id)
);

CREATE TABLE packages
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    name          VARCHAR(50)                             NOT NULL,
    description   VARCHAR(500),
    base_price    DOUBLE PRECISION                        NOT NULL,
    max_employees INTEGER                                 NOT NULL,
    CONSTRAINT pk_packages PRIMARY KEY (id)
);

CREATE TABLE package_features
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    package_id BIGINT                                  NOT NULL,
    feature_id BIGINT                                  NOT NULL,
    enabled    BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_packagefeatures PRIMARY KEY (id)
);

CREATE TABLE subscriptions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    tenant_id     BIGINT                                  NOT NULL,
    package_id    BIGINT                                  NOT NULL,
    start_date    date                                    NOT NULL,
    end_date      date                                    NOT NULL,
    billing_cycle VARCHAR(20)                             NOT NULL,
    amount        DOUBLE PRECISION                        NOT NULL,
    status        VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_subscriptions PRIMARY KEY (id)
);

CREATE TABLE tenants
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    name            VARCHAR(100)                            NOT NULL,
    domain          VARCHAR(100),
    subdomain       VARCHAR(100)                            NOT NULL,
    logo_url        VARCHAR(255),
    primary_color   VARCHAR(20),
    secondary_color VARCHAR(20),
    active          BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_tenants PRIMARY KEY (id)
);

ALTER TABLE features
    ADD CONSTRAINT uc_features_code UNIQUE (code);

ALTER TABLE package_features
    ADD CONSTRAINT uc_packagefeatures_feature UNIQUE (feature_id);

ALTER TABLE package_features
    ADD CONSTRAINT uc_packagefeatures_package UNIQUE (package_id);

ALTER TABLE tenants
    ADD CONSTRAINT uc_tenant_subdomain UNIQUE (subdomain);

ALTER TABLE package_features
    ADD CONSTRAINT FK_PACKAGEFEATURES_ON_FEATURES FOREIGN KEY (feature_id) REFERENCES features (id);

ALTER TABLE package_features
    ADD CONSTRAINT FK_PACKAGEFEATURES_ON_PACKAGES FOREIGN KEY (package_id) REFERENCES packages (id);

ALTER TABLE subscriptions
    ADD CONSTRAINT FK_SUBSCRIPTIONS_ON_PACKAGES FOREIGN KEY (package_id) REFERENCES packages (id);

ALTER TABLE subscriptions
    ADD CONSTRAINT FK_SUBSCRIPTIONS_ON_TENANTS FOREIGN KEY (tenant_id) REFERENCES tenants (id);

ALTER TABLE users
    ALTER COLUMN password TYPE VARCHAR(100) USING (password::VARCHAR(100));

ALTER TABLE users
    ALTER COLUMN role TYPE VARCHAR(50) USING (role::VARCHAR(50));

ALTER TABLE users
    ALTER COLUMN username TYPE VARCHAR(50) USING (username::VARCHAR(50));