CREATE TABLE feature
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    name        VARCHAR(100)                            NOT NULL,
    code        VARCHAR(50)                             NOT NULL,
    description VARCHAR(500),
    module      VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_feature PRIMARY KEY (id)
);

CREATE TABLE package
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    name          VARCHAR(50)                             NOT NULL,
    description   VARCHAR(500),
    base_price    DOUBLE PRECISION                        NOT NULL,
    max_employees INTEGER                                 NOT NULL,
    CONSTRAINT pk_package PRIMARY KEY (id)
);

CREATE TABLE package_feature
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    package_id BIGINT                                  NOT NULL,
    feature_id BIGINT                                  NOT NULL,
    enabled    BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_packagefeature PRIMARY KEY (id)
);

CREATE TABLE subscription
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    tenant_id     BIGINT                                  NOT NULL,
    package_id    BIGINT                                  NOT NULL,
    start_date    date                                    NOT NULL,
    end_date      date                                    NOT NULL,
    billing_cycle VARCHAR(20)                             NOT NULL,
    amount        DOUBLE PRECISION                        NOT NULL,
    status        VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_subscription PRIMARY KEY (id)
);

CREATE TABLE tenant
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    name            VARCHAR(100)                            NOT NULL,
    domain          VARCHAR(100),
    subdomain       VARCHAR(100)                            NOT NULL,
    logo_url        VARCHAR(255),
    primary_color   VARCHAR(20),
    secondary_color VARCHAR(20),
    active          BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_tenant PRIMARY KEY (id)
);

ALTER TABLE feature
    ADD CONSTRAINT uc_feature_code UNIQUE (code);

ALTER TABLE package_feature
    ADD CONSTRAINT uc_packagefeature_feature UNIQUE (feature_id);

ALTER TABLE package_feature
    ADD CONSTRAINT uc_packagefeature_package UNIQUE (package_id);

ALTER TABLE tenant
    ADD CONSTRAINT uc_tenant_subdomain UNIQUE (subdomain);

ALTER TABLE package_feature
    ADD CONSTRAINT FK_PACKAGEFEATURE_ON_FEATURE FOREIGN KEY (feature_id) REFERENCES feature (id);

ALTER TABLE package_feature
    ADD CONSTRAINT FK_PACKAGEFEATURE_ON_PACKAGE FOREIGN KEY (package_id) REFERENCES package (id);

ALTER TABLE subscription
    ADD CONSTRAINT FK_SUBSCRIPTION_ON_PACKAGE FOREIGN KEY (package_id) REFERENCES package (id);

ALTER TABLE subscription
    ADD CONSTRAINT FK_SUBSCRIPTION_ON_TENANT FOREIGN KEY (tenant_id) REFERENCES tenant (id);

ALTER TABLE users
    ALTER COLUMN password TYPE VARCHAR(100) USING (password::VARCHAR(100));

ALTER TABLE users
    ALTER COLUMN role TYPE VARCHAR(50) USING (role::VARCHAR(50));

ALTER TABLE users
    ALTER COLUMN username TYPE VARCHAR(50) USING (username::VARCHAR(50));