spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/vixhr_reporting
    username: ${DOCKER_DB_USERNAME:vixhruser}
    password: ${DOCKER_DB_PASSWORD:vixhrpassword}
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: report-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: reporting-service

server:
  max-http-request-header-size: 10KB