CREATE TABLE attendance_records
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    employee_id        BIGINT                                  NOT NULL,
    date               date                                    NOT NULL,
    check_in_time      time WITHOUT TIME ZONE                  NOT NULL,
    check_out_time     time WITHOUT TIME ZONE                  NOT NULL,
    check_in_longitude DOUBLE PRECISION                        NOT NULL,
    check_in_latitude  DOUBLE PRECISION                        NOT NULL,
    checkout_longitude DOUBLE PRECISION                        NOT NULL,
    checkout_latitude  DOUBLE PRECISION                        NOT NULL,
    check_in_address   VARCHAR(100),
    checkout_address   VARCHAR(100),
    check_in_device_id VARCHAR(100),
    checkout_device_id VARCHAR(100),
    check_in_ip        VARCHAR(45),
    checkout_ip        VARCHAR(45),
    status             VARCHAR(20)                             NOT NULL,
    is_overtime        BOOLEAN                                 NOT NULL,
    overtime_hours     DOUBLE PRECISION                        NOT NULL,
    notes              VARCHAR(500),
    CONSTRAINT pk_attendance_records PRIMARY KEY (id)
);

CREATE TABLE employee_overtime
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    employee_id        BIGINT                                  NOT NULL,
    overtime_policy_id BIGINT                                  NOT NULL,
    date               date                                    NOT NULL,
    start_time         time WITHOUT TIME ZONE                  NOT NULL,
    end_time           time WITHOUT TIME ZONE                  NOT NULL,
    hours              DOUBLE PRECISION                        NOT NULL,
    rate               DOUBLE PRECISION                        NOT NULL,
    status             VARCHAR(20),
    notes              VARCHAR(500),
    approved_by        BIGINT,
    approved_date      date,
    CONSTRAINT pk_employee_overtime PRIMARY KEY (id)
);

CREATE TABLE geofence_locations
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    company_id BIGINT                                  NOT NULL,
    name       VARCHAR(100)                            NOT NULL,
    latitude   DOUBLE PRECISION                        NOT NULL,
    longitude  DOUBLE PRECISION                        NOT NULL,
    radius     INTEGER                                 NOT NULL,
    address    VARCHAR(255),
    is_active  BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_geofence_locations PRIMARY KEY (id)
);

CREATE TABLE overtime_clock_events
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE,
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    employee_id           BIGINT                                  NOT NULL,
    overtime_policy_id    BIGINT                                  NOT NULL,
    event_type            VARCHAR(10)                             NOT NULL,
    event_time            time WITHOUT TIME ZONE                  NOT NULL,
    latitude              DOUBLE PRECISION                        NOT NULL,
    longitude             DOUBLE PRECISION                        NOT NULL,
    address               VARCHAR(100),
    device_id             VARCHAR(100),
    ip_address            VARCHAR(45),
    location_verified     BOOLEAN                                 NOT NULL,
    geo_fence_location_id BIGINT                                  NOT NULL,
    notes                 VARCHAR(500),
    CONSTRAINT pk_overtimeclockevents PRIMARY KEY (id)
);

ALTER TABLE attendance_records
    ADD CONSTRAINT uc_2d59693229e685c17daefd1b2 UNIQUE (employee_id, date);

ALTER TABLE overtime_clock_events
    ADD CONSTRAINT FK_OVERTIMECLOCKEVENTs_ON_GEO_FENCE_LOCATION FOREIGN KEY (geo_fence_location_id) REFERENCES geofence_locations (id);