spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/vixhr_employee
    username: ${DOCKER_DB_USERNAME:vixhruser}
    password: ${DOCKER_DB_PASSWORD:vixhrpassword}
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: employee-service

server:
  max-http-request-header-size: 10KB